#  pre-commit run --all-files 可以在commit之前校验一下
repos:
  - repo: https://github.com/fluttercommunity/import_sorter
    rev: "master"
    hooks:
      - id: dart-import-sorter
  - repo: https://github.com/LqDeveloper/flutter_pre_commit
    rev: "main"
    hooks:
      - id: flutter-analyze
      - id: dart-format
#      - id: dart-fix